# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('num_cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(default='example@email.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta_Alumno',
            fields=[
                ('folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta_Profesor',
            fields=[
                ('folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Generación')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Carrera',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio_Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_oficina', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado el')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Laboratorista',
                'verbose_name_plural': 'Laboratoristas',
            },
        ),
        migrations.CreateModel(
            name='Materia_Laboratorio',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('nombre', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('materia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Materia_Laboratorio', verbose_name='Materia Laboratorio')),
                ('predecesora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Practica', verbose_name='Práctica Predecesora')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactivo', models.CharField(max_length=300)),
                ('sino', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rfc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('num_empleado', models.IntegerField(verbose_name='Número de Empleado')),
                ('correo_e', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_oficina', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado el')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('porque', models.CharField(max_length=500)),
                ('id_Encuesta_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Encuesta_Alumno')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100, verbose_name='Turno')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_clave_mat_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Materia_Laboratorio', verbose_name='Clave Materia'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Grupos_Carrera', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Periodo', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='grupos_carrera',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Turno', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_laboratorio_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Practica'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Profesor'),
        ),
        migrations.AddField(
            model_name='encuesta_alumno',
            name='id_laboratorio_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Generacion', verbose_name='Generación'),
        ),
    ]
