# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_oficina', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado el')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda_Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hora_ini', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('hora_fin', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('reagendamiento', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('num_cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(default='example@email.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=20, verbose_name='Día')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
            },
        ),
        migrations.CreateModel(
            name='Encuesta_Alumno',
            fields=[
                ('folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Generación')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Carrera',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('aula', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio_Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_oficina', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado el')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Laboratorista',
                'verbose_name_plural': 'Laboratoristas',
            },
        ),
        migrations.CreateModel(
            name='Materia_Laboratorio',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('nombre', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('materia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Materia_Laboratorio', verbose_name='Materia Laboratorio')),
                ('predecesora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Practica', verbose_name='Práctica Predecesora')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rfc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('num_empleado', models.IntegerField(verbose_name='Número de Empleado')),
                ('correo_e', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('telefono_casa', models.CharField(max_length=14)),
                ('telefono_oficina', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Creado el')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='RespuestaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('a', 'Excelente'), ('b', 'Bueno'), ('c', 'Regular'), ('d', 'Malo')], max_length=20)),
                ('cumplio_objetivo', models.CharField(choices=[('si', 'No'), ('no', 'Sí')], max_length=4)),
                ('apertura_oportuna', models.CharField(choices=[('si', 'No'), ('no', 'Sí')], max_length=4)),
                ('apertura_porque', models.CharField(blank=True, max_length=150, null=True)),
                ('permanencia_enpractica', models.CharField(choices=[('si', 'No'), ('no', 'Sí')], max_length=4)),
                ('permanencia_porque', models.CharField(blank=True, max_length=150, null=True)),
                ('colaboracion_practica', models.CharField(choices=[('si', 'No'), ('no', 'Sí')], max_length=4)),
                ('colaboracion_porque', models.CharField(blank=True, max_length=150, null=True)),
                ('entrega_equipo', models.CharField(choices=[('si', 'No'), ('no', 'Sí')], max_length=4)),
                ('entrega_porque', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('encuesta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Agenda_Practica')),
                ('id_laboratorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorista')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100, verbose_name='Turno')),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_clave_mat_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Materia_Laboratorio', verbose_name='Clave Materia'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Grupos_Carrera', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Periodo', verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Profesor', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='grupos_carrera',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Turno', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='encuesta_alumno',
            name='id_laboratorio_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Carrera', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Generacion', verbose_name='Generación'),
        ),
        migrations.AddField(
            model_name='agenda_practica',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='agenda_practica',
            name='laboratorio_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio_Horario', verbose_name='Laboratorio Horario'),
        ),
        migrations.AddField(
            model_name='agenda_practica',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Practica', verbose_name='Práctica'),
        ),
        migrations.AddField(
            model_name='agenda_practica',
            name='rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Profesor', verbose_name='Profesor'),
        ),
    ]
