# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0002_auto_20190117_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta_alumno',
            name='id_alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Alumno'),
        ),
        migrations.AlterField(
            model_name='encuesta_alumno',
            name='id_laboratorio_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorio_Horario'),
        ),
        migrations.AlterField(
            model_name='encuesta_alumno',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
