# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0002_remove_encuestaprofesor_cuestionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestapregunta',
            name='cuestionario',
        ),
    ]
