# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0003_remove_encuestapregunta_cuestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('a', 'Excelente'), ('b', 'Bueno'), ('c', 'Regular'), ('d', 'Malo')], max_length=20)),
                ('cumplio_objetivo', models.CharField(choices=[(0, 'No'), (2, 'Sí')], max_length=4)),
                ('apertura_oportuna', models.CharField(choices=[(0, 'No'), (2, 'Sí')], max_length=4)),
                ('apertura_porque', models.CharField(max_length=150)),
                ('permanencia_enpractica', models.CharField(choices=[(0, 'No'), (2, 'Sí')], max_length=4)),
                ('permanencia_porque', models.CharField(max_length=150)),
                ('colaboracion_practica', models.CharField(choices=[(0, 'No'), (2, 'Sí')], max_length=4)),
                ('colaboracion_porque', models.CharField(max_length=150)),
                ('entrega_equipo', models.CharField(choices=[(0, 'No'), (2, 'Sí')], max_length=4)),
                ('entrega_porque', models.CharField(max_length=150)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.EncuestaProfesor')),
                ('id_laboratorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Laboratorista')),
            ],
        ),
        migrations.DeleteModel(
            name='EncuestaNombre',
        ),
        migrations.RemoveField(
            model_name='encuestarespuesta',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='encuestarespuesta',
            name='reactivo',
        ),
        migrations.DeleteModel(
            name='EncuestaPregunta',
        ),
        migrations.DeleteModel(
            name='EncuestaRespuesta',
        ),
    ]
