# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_auto_20190207_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='apertura_porque',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='colaboracion_porque',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='encuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.EncuestaProfesor'),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='entrega_porque',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='permanencia_porque',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
