# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_auto_20190207_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='apertura_porque',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='colaboracion_porque',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='entrega_porque',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaprofesor',
            name='permanencia_porque',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
