# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('num_cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField()),
                ('email', models.EmailField(default='example@email.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Inscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_aviso', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField()),
                ('inicio_aviso', models.DateTimeField(max_length=100)),
                ('fin_aviso', models.DateTimeField(max_length=100)),
                ('rol_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dia_No_Laborable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta_Alumno',
            fields=[
                ('folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=500)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta_Profesor',
            fields=[
                ('folio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Fecha_Limite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('rol_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_formato', models.CharField(max_length=100)),
                ('nombre_formato', models.CharField(max_length=100)),
                ('rol_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Carrera',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('aula', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio_Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.CharField(max_length=200)),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Laboratorio',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Apoyo',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('materia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Materia_Laboratorio')),
                ('predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Practica')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactivo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rfc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('num_empleado', models.IntegerField()),
                ('correo_e', models.EmailField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('porque', models.CharField(max_length=500)),
                ('id_Encuesta_Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Encuesta_Alumno')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('porque', models.CharField(max_length=500)),
                ('id_Encuesta_Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Encuesta_Profesor')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Limite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('E_A', 'Encuesta Alumno'), ('E_P', 'Encuesta Profesor'), ('R_P', 'Reagendar_Practica')], default='Enc_Alumno', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_tipo_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Tipo_Respuesta'),
        ),
        migrations.AddField(
            model_name='personal_apoyo',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Seccion'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_clave_mat_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Materia_Laboratorio'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_dias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Dias'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Grupos_Carrera'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Horario'),
        ),
        migrations.AddField(
            model_name='laboratorio_horario',
            name='rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Profesor'),
        ),
        migrations.AddField(
            model_name='grupos_carrera',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Turno'),
        ),
        migrations.AddField(
            model_name='fecha_limite',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Tipo_Limite'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_laboratorio_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_laboratorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Laboratorista'),
        ),
        migrations.AddField(
            model_name='encuesta_profesor',
            name='id_practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Practica'),
        ),
        migrations.AddField(
            model_name='encuesta_alumno',
            name='id_laboratorio_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='alumno_inscrito',
            name='id_laboratorio_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Laboratorio_Horario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_generacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PagGestion.Generacion'),
        ),

    ]
